### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by geopayme** [doged/electrum-doged#1]
Is there any Doged electrum servers available to test with an Android Wallet?

**Comment by doged** [comment]
@geopayme our android wallet does connect to our electrum server

**Comment by doged** [comment]
electrum-doged.space is one of our electrum servers

**Comment by geopayme** [comment]
What port are you using? I tried port 50001 no luck I get a CLOSED message.

**Comment by geopayme** [comment]
Im working on the UberPay wallet... Im part of the Mazacoin team... we deployed mazacoin on the uberpay wallet few weeks ago.

**Comment by doged** [comment]
@geopayme ah, so you're the one thats been trying to get on a non ssl port with ssl ;]

50001 is a non-ssl port..  electrum server is up and hasnt gone down in months.. its in #electrum-doged on freenode =]

let me know when you guys complete that project and ill relay it to the doged community =]

**Comment by doged** [comment]
i suppose 50002 would be for ssl, but i didnt set that up, since the android wallet and client and coinomi wallets dont use it

**Comment by doged** [comment]
yeah electrum-doged.space:50001 is open, and working on electrum client and android wallet right now. just checked. i saw in the logs tho that an ssl was trying to connect via 50001

**Comment by geopayme** [comment]
Hi, I was hoping you can answer a question, we got the coin to work on the wallet, but it seems the value is off. I send 1.00000000 minus 0.1 fee and the wallet received 0.0090

Maybe the values here are incorrect?

```
    feePerKb = value(10000000);
    minNonDust = value(1000000);
    softDustLimit = value(10000000); // TODO Verify values 1 DOGED
```

Thanks

**Comment by bitspill** [comment]
@geopayme I believe the discrepancy comes in with how many "satoshi" are in 1 coin, bitcoin by default uses 100million, DogeD uses 1million, which leads to your decimal being in the wrong location.

https://github.com/doged/dogedsource/blob/master/src/util.h#L35
https://github.com/bitcoin/bitcoin/blob/master/src/amount.h#L16

**Comment by geopayme** [comment]
issue resolved...

**Comment by doged** [comment]
@geopayme great! dont forget, we have an electrum service running on tor and i2p as well, for complete anonymity :see_no_evil:

**Comment by doged** [comment]
those electrum clients have their own repo's here: 

https://github.com/doged/electrum-doged-i2p

and 

https://github.com/doged/electrum-doged-tor

**Comment by geopayme** [comment]
UberPay already updated with DOGED and available in Google Play! - will be
posting update on on twitter!

On Fri, Oct 23, 2015 at 5:26 PM, DogecoinDark notifications@github.com
wrote:

> @geopayme https://github.com/geopayme great! dont forget, we have an
> electrum service running on tor and i2p as well, for complete anonymity [image:
> :see_no_evil:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/doged/electrum-doged/issues/1#issuecomment-150589455.

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by doged** [comment]
@geopayme i will let the community know right now, thanks!

**Comment by geopayme** [comment]
Happy to participate!

On Fri, Oct 23, 2015 at 5:47 PM, DogecoinDark notifications@github.com
wrote:

> @geopayme https://github.com/geopayme i will let the community know
> right now, thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/doged/electrum-doged/issues/1#issuecomment-150595524.

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by geopayme** [comment]
After you evaluate it, I look forward to your review on Google Play.

On Fri, Oct 23, 2015 at 5:58 PM, Adonis Valamontes tony@geopay.me wrote:

> Happy to participate!
> 
> On Fri, Oct 23, 2015 at 5:47 PM, DogecoinDark notifications@github.com
> wrote:
> 
> > @geopayme https://github.com/geopayme i will let the community know
> > right now, thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/doged/electrum-doged/issues/1#issuecomment-150595524
> > .
> 
> ## 
> 
> Geopay.me Inc.
> 
> _"don't need to know everything, I just need to know where to find it."__A.
> Einstein._
> If you need to reach your people really fast, there's no better way to do
> it than with "mobile".
> 
> Mobile is direct, accurate, and personal.
> 
> This email may contain confidential and/or privileged information. If you
> are not the intended recipient (or have received this email by mistake),
> please notify the sender immediately and destroy this email. Any
> unauthorised copying, disclosure or distribution of the material in this
> email is strictly prohibited.
> 
> Email transmission security and error-free status cannot be guaranteed as
> information could be intercepted, corrupted, destroyed, delayed,
> incomplete, or contain viruses. The sender therefore does not accept
> liability for any errors or omissions in the contents of this message
> which may arise as a result of email transmission.

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by geopayme** [comment]
Any updated when the DOGED electrum server will be up again?

**Comment by bitspill** [comment]
EL_Doged is still connected to #electrum_doged and it looks like the last loss of connection was on October 20th, it should be online and connectable now.

**Comment by geopayme** [comment]
I see electrum-doged.space:50001 still closed!

On Sat, Oct 31, 2015 at 1:13 PM, bitspill notifications@github.com wrote:

> EL_Doged is still connected to #electrum_doged and it looks like the last
> loss of connection was on October 20th, it should be online and connectable
> now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/doged/electrum-doged/issues/1#issuecomment-152723977.

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by doged** [comment]
@geopayme i had to restart the daemon on that server, its back up now. thanks for the notice!

**Comment by geopayme** [comment]
We run a Monitor Service for all the coins in UberPay... keeps on our toes!

On Sat, Oct 31, 2015 at 4:45 PM, DogecoinDark notifications@github.com
wrote:

> @geopayme https://github.com/geopayme i had to restart the daemon on
> that server, its back up now. thanks for the notice!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/doged/electrum-doged/issues/1#issuecomment-152740494.

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by justinvforvendetta** [comment]
excellent! @geopayme is that you trying to connect to the bolivarcoin electrum server?

**Comment by geopayme** [comment]
Yes

**Comment by geopayme** [comment]
Hello any status when the DOGED electrum server will back up and running
again? electrum-doged.space:50001

On Sat, Oct 31, 2015 at 10:34 PM, Adonis Valamontes tony@geopay.me wrote:

> Yes
> On Oct 31, 2015 10:13 PM, "sunerok" notifications@github.com wrote:
> 
> > excellent! @geopayme https://github.com/geopayme is that you trying to
> > connect to the bolivarcoin electrum server?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/doged/electrum-doged/issues/1#issuecomment-152767686
> > .

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by doged** [comment]
it never left the irc channel, but i just restarted it.

**Comment by geopayme** [comment]
Thanks!

On Thu, Nov 5, 2015 at 7:28 PM, DogecoinDark notifications@github.com
wrote:

> it never left the irc channel, but i just restarted it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/doged/electrum-doged/issues/1#issuecomment-154130718.

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by geopayme** [comment]
I got a message from a user that your server is off line any news as to
when its going to be back online?

[image: Inline image 1]

On Thu, Nov 5, 2015 at 9:16 PM, Adonis Valamontes tony@geopay.me wrote:

> Thanks!
> 
> On Thu, Nov 5, 2015 at 7:28 PM, DogecoinDark notifications@github.com
> wrote:
> 
> > it never left the irc channel, but i just restarted it.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/doged/electrum-doged/issues/1#issuecomment-154130718
> > .
> 
> ## 
> 
> Geopay.me Inc.
> 
> _"don't need to know everything, I just need to know where to find it."__A.
> Einstein._
> If you need to reach your people really fast, there's no better way to do
> it than with "mobile".
> 
> Mobile is direct, accurate, and personal.
> 
> This email may contain confidential and/or privileged information. If you
> are not the intended recipient (or have received this email by mistake),
> please notify the sender immediately and destroy this email. Any
> unauthorised copying, disclosure or distribution of the material in this
> email is strictly prohibited.
> 
> Email transmission security and error-free status cannot be guaranteed as
> information could be intercepted, corrupted, destroyed, delayed,
> incomplete, or contain viruses. The sender therefore does not accept
> liability for any errors or omissions in the contents of this message
> which may arise as a result of email transmission.

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by justinvforvendetta** [comment]
@geopayme  its back up. it was still in irc, but i gave it a reboot. thanks for the heads up!

**Comment by geopayme** [comment]
No Problem!

On Fri, Dec 4, 2015 at 2:48 AM, sunerok notifications@github.com wrote:

> @geopayme https://github.com/geopayme its back up. it was still in irc,
> but i gave it a reboot. thanks for the heads up!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/doged/electrum-doged/issues/1#issuecomment-161839278.

## 

Geopay.me Inc.

_"don't need to know everything, I just need to know where to find it."__A.
Einstein._
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by geopayme** [comment]
Your DOGED electrum server seem to run inconsistently, its down again! - I have folks emailing me that use the UberPay wallet

**Comment by doged** [comment]
thats odd, im going to leave it in console mode so i can see what's happening, because it ran for 6 months straight for no problem, then suddenly lately its having issues with uberpay but staying in irc? sounds strange.

**Comment by doged** [comment]
ok it looks like you or one of your users is trying to connect via ssl, which is not enabled on that server.

**Comment by doged** [comment]
ERROR:electrum-doged:cannot start TCP session[Errno 336265218] _ssl.c:355: error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib ('108.44.238.26', 37251)

that ip is from verizon, and its trying to connect via ssl.

**Comment by doged** [comment]
the problem is "all_seeing_eye" is trying to connect to its ssl port i think.

**Comment by doged** [comment]
ok i fixed it, i disabled the ssl port entirely.
