### ISSUE TITLE
Transferred 2791.790412 XVG to electrum-XVG and was pending for 2 days then expired

### ISSUE THREAD

**Issue by Nullhk** [doged/electrum-doged#11]
I have lost all of my XVG while attempting to transfer to my wallet.

It was spent pending for 2 days and then expired this morning.

The client keeps connecting and disconnect frequently.  I am looking for my funds lost in transit now

1. I sent the funds to the address on my electrum client before it actually managed to connect to the network

2. I changed the address to elec2.verge-blockchain.com as none of the default addresses worked

3. I waited for 2 days and the funds never got verified.  Email me for the unblocked screenshots
![11](https://user-images.githubusercontent.com/34778041/34309826-0e5876da-e722-11e7-9fb2-3135b004af14.PNG)

**Comment by justinvforvendetta** [comment]
the funds are verified almost immediately after arriving. where it says "unverified" is just a cosmetic glitch. your coins are already spendable.

should be fixed in 2.6, and itll be out soon
