### ISSUE TITLE
Issues with Electrum Wallet and Verge Blockchain Download

### ISSUE THREAD

**Issue by revizionary1** [doged/electrum-doged#13]
My Electrum wallet is not online. I now know this is very common. I downloaded the Verge blockchain which contains no exe or app to extract from the zip file and no instructions on how to sync with Windows. I am having the same issue and there are Verge XVG I had sent to my wallet from Changelly which are not showing up because the wallet is still not online. I have no idea how to verify where it is on the blockchain because I cannot get the zip file to extract properly. I have a Lisk Nano wallet and other wallets and they were seamless. This wallet (The Electrum) is unbelievably bad. How is this user friendly? What company releases a product with all of these glitches? It is very easy to release a wallet that syncs to the network a user is using. Very, very easy to write that code.

Please explain how to extract the files so they will go to a program where I can view where my transaction is on the blockchain and I can back this up on a USB until I can sync my wallet. Good grief you have made this so unbelievably labor intensive and frustrating. You need an .exe or an .app file that comes out of a zip file in order to create a workable program in Windows, guys. Your product does not have that. All it has is windat and data files that cannot execute or open themselves and windat opener says they are defective. I have downloaded from both sites on the Verge website and they linked me to here if I had issues:

https://verge-blockchain.com/down

https://vergecurrency.com/

Stuart Hill

Here is the email notification where I sent my Litecoin to Changelly for the Verge:

You just sent                             0.25951807 LTC
--
 
 
 
Congratulations! You have successfully sent 0.25951807 LTC (worth $72.87 USD) to LguHiosse96HKi91YDQctsStFFYbFdQeGH using Coinbase.                     To facilitate this transaction, you paid 0.00118799 LTC (worth $0.33 USD) in network fees.                                                      This withdrawal is being sent to an address ("LguHiosse96HKi91YDQctsStFFYbFdQeGH") that you haven't previously used.
 

Here is the address in my Electrum wallet where it says to report all issues or glitches:

https://github.com/vergecurrency/electrum-xvg/pulls

Please advise me what to do. How I can get this straightened out now. You need to be marketing a product that is merchantable. That means it works AS IS and for a particular purpose and with no bugs that cause it to be defective. So far, neither your Electrum Wallet or the Blockchain have shown to be marketable to me.

Stuart Hill

**Comment by revizionary1** [comment]
An update...

Somehow I managed to connect the roaming update to the wallet and my amount of Verge was credited to my wallet during the time it was syncing online. However, it is back offline. I would like to get another wallet and purchase some more Verge for my family. Any advice on how to avoid these issues in the future of not connecting? See my original issue posted above. I just wanted you to know the amount of 263.213663 had been credited to my Electrum wallet.

Stuart Hill

**Comment by justinvforvendetta** [comment]
see the latest tweets for more electrum servers, as the default ones have completely filled with users. we have more on the way too!
