### ISSUE TITLE
Why does the Electrum wallet take so long to connect to the blockchain...

### ISSUE THREAD

**Issue by adambee23** [doged/electrum-doged#2]
The verge electrum wallet is fantastic. It simple to use, doesnt take up much space and its fast... 

The only problem is it doesnt connect to the blockchain instantly. This is a problem. Especially if you need to send or receive Verge. 

Can this be fixed? Does it need to be upgraded? I know other people are having the same issues. 

Someone with expertise please look into this for the Verge Community

Thank you

**Comment by pickorlose** [comment]
I am having the same issue on my PC. When I first installed the wallet, it connected pretty fast. Now, I  have not been able to connect for three days. Should I change server options ( I only have 2 showing)? If so, how do we do that?

**Comment by justinvforvendetta** [comment]
i would try a different server. there are several.

elec2.verge-blockchain.com
electrum-xvg.stream
electrum-xvg.party
electrum-verge.xyz
i cant remember the rest off hand.
