### ISSUE TITLE
XVG transaction still pending for over 2 months

### ISSUE THREAD

**Issue by kojib** [doged/electrum-doged#8]
I've tried re-downloading, changing servers to connect Electrum Verge Wallet 2.4.1 however transactions are still pending (for 2+months) and unverified. Please help.

**Comment by justinvforvendetta** [comment]
thats just a cosmetic bug. they are spendable the moment they arrive lol it will be fixed we hope in the next release of 2.6

**Comment by kojib** [comment]
ok. thanks
