### ISSUE TITLE
Do I have Verge or not

### ISSUE THREAD

**Issue by Florian9000** [doged/electrum-doged#9]
Hello there,

I see my balance and I also see on my wallet the balance I bought. But the problem is with history I see: Status: -1 confirmations and also Date: pending. When I look it up the blockchain it says conformations around 14k... I am using Electrum by the way.

I just dont know what is going on, do I have or not? Can someone help me? Thanks.

Flo

**Comment by justinvforvendetta** [comment]
yes, the "unverified" status is just a bug. its verified once it shows up.
